library/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import BookViewSet, CommentViewSet, GenreViewSet

app_name = 'api'

router = DefaultRouter()

router.register('books', BookViewSet)
router.register('genres', GenreViewSet)
router.register(r'books/(?P<book_id>\d+)/', BookViewSet)
router.register(
    r'books/(?P<book_id>\d+)/comments',
    CommentViewSet,
    basename='comments'
)

urlpatterns = [
    path('', include(router.urls)),
]

library/book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'book'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # path('book/', views.book_list),
    path('books/<int:book_id>/', views.post_detail, name='book_detail'),
    path(
        'books/<int:book_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'books/<int:book_id>/favorite/',
        views.add_to_favorite,
        name='add_to_favorite'
    ),
    path(
        'books/<int:book_id>/unfavorite/',
        views.delete_from_favorite,
        name='delete_from_favorite'
    ),
    path(
        '/favorites/',
        views.favorites,
        name='favorites'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

library/library/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('api-token-auth/', views.obtain_auth_token),
    path('', include('book.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
]

library/book/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Genre(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name='Название',
        unique=True,
    )
    slug = models.SlugField('Слаг', unique=True)

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
        ordering = ('-name',)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name='Описание',
    )
    author = models.TextField('Автор')
    genres = models.ManyToManyField(
        Genre,
        verbose_name='Жанр',
        related_name='genres',
    )
    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='books/',
        blank=True
    )
    # Аргумент upload_to указывает директорию,
    # в которую будут загружаться пользовательские файлы.

    users = models.ManyToManyField(
        User,
        related_name='favorite_books',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'
        ordering = ('title',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Добавьте Ваш комментарий'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-pub_date']

library/book/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }
        help_texts = {
            'text': 'Добавьте Ваш комментарий',
        }

    def __str__(self):
        return self.text

library/book/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm
from .models import Book


def index(request):
    post_list = Book.objects.order_by('-id')
    paginator = Paginator(post_list, settings.POST_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if request.user.is_authenticated:
        favorite_post_list = Book.objects.filter(users=request.user)
        context = {
            'page_obj': page_obj,
            'favorite_post_list': favorite_post_list,
        }
        return render(request, 'book/index.html', context)
    context = {
            'page_obj': page_obj,
        }
    return render(request, 'book/index.html', context)


def author(request):
    template = 'about/author.html'
    return render(request, template)


def post_detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    form = CommentForm()
    comments = book.comments.all()
    genres = book.genres.all()
    context = {
        'books': book,
        'form': form,
        'comments': comments,
        'genres': genres,
    }
    return render(request, 'book/book_detail.html', context)


@login_required
def add_comment(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    form = CommentForm(request.POST or None)
    if request.is_ajax():
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.book = book
            comment.save()
            return JsonResponse({"book": comment.book.pk}, status=200)
    return redirect('book:book_detail', book_id=book_id)


@login_required
def add_to_favorite(request, book_id):
    if request.user.is_authenticated:
        user = request.user
        user.favorite_books.add(get_object_or_404(Book, pk=book_id))
        return redirect('book:index')
    return redirect('users:login')


@login_required
def delete_from_favorite(request, book_id):
    following = Book.objects.filter(pk=book_id)
    if following.exists():
        request.user.favorite_books.remove(get_object_or_404(Book, pk=book_id))
    return redirect('book:index')


@login_required
def favorites(request):
    user = request.user
    post_list = user.favorite_books.all()
    paginator = Paginator(post_list, settings.POST_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'book/favorites.html', context)

library/templates/book/includes/comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form id="contactForm" method="post">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button id="id_button_save" type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4" >
    <div class="media-body" >
      <h5 class="mt-0">
        <a href="">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}
{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script>
      $(document).ready(function () {
          // отслеживаем событие отправки формы
          $('#contactForm').submit(function () {
              // создаем AJAX-вызов
              $.ajax({
                  data: $(this).serialize(), // получаем данные формы
                  type: $(this).attr('method'), // GET или POST
                  url: "{% url 'book:add_comment' books.id %}",
                  // если успешно, то
                  success:function(html){
                    $("#content").load(location.href + " #content")
                      },
                  // если ошибка, то
                  error: function (response) {
                      // предупредим об ошибке
                      alert(response.responseJSON.errors);
                      console.log(response.responseJSON.errors)
                  }
              });
              return false;
          });
      })
  </script>
{% endblock javascript %}