library/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
]

library/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import BookViewSet, CommentViewSet, GenreViewSet

app_name = 'api'

router = DefaultRouter()

router.register('books', BookViewSet)
router.register('genres', GenreViewSet)
router.register(r'books/(?P<book_id>\d+)/', BookViewSet)
router.register(
    r'books/(?P<book_id>\d+)/comments',
    CommentViewSet,
    basename='comments'
)

urlpatterns = [
    path('', include(router.urls)),
]

library/library/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('api-token-auth/', views.obtain_auth_token),
    path('', include('book.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
]

library/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'

library/templates/about/author.html
{% extends "base.html" %}
{% load static %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
  <a class="navbar-brand" href="{% url 'about:author' %}">
    <img src="{% static 'img/logo2.jpg' %}" width="60" height="60" class="d-inline-block align-top" alt="">
  </a>
</p>
{% endblock %}