library/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import BookViewSet, CommentViewSet, GenreViewSet

app_name = 'api'

router = DefaultRouter()

router.register('books', BookViewSet)
router.register('genres', GenreViewSet)
router.register(r'books/(?P<book_id>\d+)/', BookViewSet)
router.register(
    r'books/(?P<book_id>\d+)/comments',
    CommentViewSet,
    basename='comments'
)

urlpatterns = [
    path('', include(router.urls)),
]

library/book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'book'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # path('book/', views.book_list),
    path('books/<int:book_id>/', views.post_detail, name='book_detail'),
    path(
        'books/<int:book_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'books/<int:book_id>/favorite/',
        views.add_to_favorite,
        name='add_to_favorite'
    ),
    path(
        'books/<int:book_id>/unfavorite/',
        views.delete_from_favorite,
        name='delete_from_favorite'
    ),
    path(
        '/favorites/',
        views.favorites,
        name='favorites'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

library/library/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('api-token-auth/', views.obtain_auth_token),
    path('', include('book.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
]

library/book/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Genre(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name='Название',
        unique=True,
    )
    slug = models.SlugField('Слаг', unique=True)

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
        ordering = ('-name',)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name='Описание',
    )
    author = models.TextField('Автор')
    genres = models.ManyToManyField(
        Genre,
        verbose_name='Жанр',
        related_name='genres',
    )
    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='books/',
        blank=True
    )
    # Аргумент upload_to указывает директорию,
    # в которую будут загружаться пользовательские файлы.

    users = models.ManyToManyField(
        User,
        related_name='favorite_books',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'
        ordering = ('title',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Добавьте Ваш комментарий'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-pub_date']

library/book/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }
        help_texts = {
            'text': 'Добавьте Ваш комментарий',
        }

    def __str__(self):
        return self.text

library/book/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm
from .models import Book


def index(request):
    post_list = Book.objects.order_by('-id')
    paginator = Paginator(post_list, settings.POST_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if request.user.is_authenticated:
        favorite_post_list = Book.objects.filter(users=request.user)
        context = {
            'page_obj': page_obj,
            'favorite_post_list': favorite_post_list,
        }
        return render(request, 'book/index.html', context)
    context = {
            'page_obj': page_obj,
        }
    return render(request, 'book/index.html', context)


def author(request):
    template = 'about/author.html'
    return render(request, template)


def post_detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    form = CommentForm()
    comments = book.comments.all()
    genres = book.genres.all()
    context = {
        'books': book,
        'form': form,
        'comments': comments,
        'genres': genres,
    }
    return render(request, 'book/book_detail.html', context)


@login_required
def add_comment(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    form = CommentForm(request.POST or None)
    if request.is_ajax():
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.book = book
            comment.save()
            return JsonResponse({"book": comment.book.pk}, status=200)
    return redirect('book:book_detail', book_id=book_id)


@login_required
def add_to_favorite(request, book_id):
    if request.user.is_authenticated:
        user = request.user
        user.favorite_books.add(get_object_or_404(Book, pk=book_id))
        return redirect('book:index')
    return redirect('users:login')


@login_required
def delete_from_favorite(request, book_id):
    following = Book.objects.filter(pk=book_id)
    if following.exists():
        request.user.favorite_books.remove(get_object_or_404(Book, pk=book_id))
    return redirect('book:index')


@login_required
def favorites(request):
    user = request.user
    post_list = user.favorite_books.all()
    paginator = Paginator(post_list, settings.POST_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'book/favorites.html', context)

library/templates/book/book_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Книга "{{ books.title }}"
{% endblock %}
{% block content %}       
      <div class="row" id="content">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Автор: {{ books.author }}
              </li>
            <li class="list-group-item">
                Жанры: {% for genre in genres %}
                <div class="badge bg-primary text-wrap" style="width: 6rem;">
                  {{ genre.name }}
                </div>
                {% endfor %}
            </li>
            <li class="list-group-item">
                {% thumbnail books.image "1000x1000" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          
          <p>
           {{ books.description }}
          </p>
          
        </article>
        {% include 'book/includes/comment.html' %}
      </div> 
{% endblock %}

library/templates/book/favorites.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% load static %}
{% block content %}
{% block title %}
  {{title}}
{% endblock %}

<div class="album py-5 bg-black">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
{% for book in page_obj %}

  <div class="col">
    <div style="height: 700px;" class="card shadow-sm">
      <a class="navbar-brand" href="{% url 'book:book_detail' book.pk %}">
      {% thumbnail book.image "600x600" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      </a>
      <div class="card-body">
        <ul>
          <li>
            Название:
            {{ book.title }}
          </li>
          <li>
            Автор: 
            <a>{{ book.author }} </a>
          </li>
          <li>
            Жанры: 
            <a>{{ book.genres }} </a>
          </li>
        </ul>   
        <p>
          {{ book.description }} 
        </p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group align-items-end">
            <a class="btn btn-sm btn-outline-warning" href="{% url 'book:delete_from_favorite' book.pk %}" role="button">
              В избранное
            </a>
            <button type="button" class="btn btn-sm btn-outline-secondary">Оценить</button>
          </div>
          <small class="text-muted">9 mins</small>
        </div>

      </div> 
    </div>
  </div>

{% endfor %}
</div>
      </div>
    </div>
{% endblock %}

library/templates/book/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% load static %}
{% block content %}
{% block title %}
  {{title}}
{% endblock %}

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
{% for book in page_obj %}

  <div class="col">
    <div style="height: 700px;" class="card shadow-sm">
      {% thumbnail book.image "600x600" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <div class="card-body">
        <ul>
          <li>
            Название:
            {{ book.title }}
          </li>
          <li>
            Автор: 
            <a>{{ book.author }} </a>
          </li>
          <li>
            Жанры: 
            <a>{{ book.genres }} </a>
          </li>
        </ul>   
        <p>
          {{ book.description }} 
        </p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group align-items-end">
            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
          </div>
          <small class="text-muted">9 mins</small>
        </div>

      </div>
    </div>
  </div>

{% endfor %}
</div>
      </div>
    </div>
{% endblock %}

library/templates/book/scores.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>Оценки</title>
  </head>
  <body>
    <header>
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <nav class="navbar navbar-light" style="background-color: blue">
        <div class="container">
          <a class="navbar-brand" href="index.html">
            <img src="img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:white">Libra</span>.com
          </a>
          <ul class="nav nav-pills">            <li class="nav-item">              
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
              href="author.html">Об авторе</a>
            </li>
            <li class="nav-item">              
                <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
                  href="readlist.html">Буду читать</a>
                </li>
              <li class="nav-item"> 
                <a class="nav-link link-light" href="password_reset.html">Изменить пароль</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link link-light" href="index.html">Выйти</a>
              </li>
              <li>
                Пользователь: user
              </li>         </ul>
        </div>
      </nav>
    </header>
    <main> 
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>Буду читать</h1>
        <hr>
        <article>
            <img src="img/book3.jpg" width="200" height="200" class="d-inline-block align-right" alt=""> 
            <ul>
              <li>
                Название: Мартин Иден
              </li>
              <li>
                Автор: Джек Лондон
              </li>
              <li>
                Дата публикации: 28 июля 1854
              </li>
            </ul> 
            <p>
              Роман Джека Лондона. Впервые был напечатан в журнале 
              «The Pacific Monthly» в 1908-1909 годах и уже в 1909 году вышел отдельной книгой в издательстве «Макмиллан компани». 
            </p>
            <a class="btn btn-lg btn-primary" href="" role="button">
              Буду читать
            </a>
            <a class="btn btn-lg btn-secondary" href="" role="button">
              Оценить
            </a>
          </article>
        <hr>
        <!-- под последним постом нет линии -->
      </div>  
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      <p>© 2023 Copyright <span style="color:red">Libra</span>.com</p>    
    </footer>
  </body>
</html>