library/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import BookViewSet, CommentViewSet, GenreViewSet

app_name = 'api'

router = DefaultRouter()

router.register('books', BookViewSet)
router.register('genres', GenreViewSet)
router.register(r'books/(?P<book_id>\d+)/', BookViewSet)
router.register(
    r'books/(?P<book_id>\d+)/comments',
    CommentViewSet,
    basename='comments'
)

urlpatterns = [
    path('', include(router.urls)),
]

library/book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'book'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # path('book/', views.book_list),
    path('books/<int:book_id>/', views.post_detail, name='book_detail'),
    path(
        'books/<int:book_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'books/<int:book_id>/favorite/',
        views.add_to_favorite,
        name='add_to_favorite'
    ),
    path(
        'books/<int:book_id>/unfavorite/',
        views.delete_from_favorite,
        name='delete_from_favorite'
    ),
    path(
        '/favorites/',
        views.favorites,
        name='favorites'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

library/library/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('api-token-auth/', views.obtain_auth_token),
    path('', include('book.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
]

library/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    )
]

library/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
    <p>© 2023 Copyright <span style="color:red">Libra</span>.com</p>    
  </footer>

library/templates/includes/header.html
{% load static %}
<header>
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: #a2d2ff">
      <div class="container">
        <a class="navbar-brand" href="{% url 'book:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:white">Libra.com</span>
        </a>

        {% with request.resolver_match.view_name as view_name %}  
        <ul class="nav nav-pills">            
          <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
            href="{% url 'about:author' %}">Об авторе</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">              
            <a class="nav-link {% if view_name  == 'book:favorites' %}active{% endif %}" 
              href="{% url 'book:favorites' %}">Избранное</a>
            </li>
            {% endif %}

          {% if request.user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:password_reset' %}">Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
          </li>
          {% endif %}   
          {% endwith %}
        </ul>
      </div>
    </nav>
  </header>